server:
  port: 9999
spring:
  application:
    name: es-article
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.137.8.13:3307/leadnews_article?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8&&allowPublicKeyRetrieval=true
    username: root
    password: 123
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.article.pojos


#自定义elasticsearch连接配置
elasticsearch:
  host: 43.137.8.13
  port: 9200
